language: node_js
node_js:
 - "7"
script:
 - echo "Deploy!"
install:
 - npm install -g firebase-tools
after_success:
 - firebase target:apply hosting bpr-certgen bpr-certgen
 - firebase deploy --project bengaluru-plog-run --token $FIREBASE_TOKEN
